[build]
  publish = "."

[[redirects]]
  from = "/browse"
  to = "/browse.html"
  status = 200

[[redirects]]
  from = "/browse-books"
  to = "/browse.html"
  status = 200

[[redirects]]
  from = "/exchange"
  to = "/exchange.html"
  status = 200

[[redirects]]
  from = "/donate"
  to = "/donate.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200
